version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    container_name: flask-basic
    links:
      - mongo

volumes:
  mongo-data:
    driver: local
